const structure = [
  {
    name: "Еськова Виктория Александровна",
    position: "D",
    phone_number: "+7 (8512) 66-74-00",
    department: "he",
    image: "http://127.0.0.1:8000/media/structures/eskova.jpg",
  },
  {
    name: "Ли Владимир Юрьевич",
    position: "N",
    phone_number: "+7 (8512) 66-74-59",
    department: "gl",
    image: null,
  },
  {
    name: "Кущенкова Юлия Сергеевна",
    position: "M",
    phone_number: "+7 (8512) 66-74-56",
    department: "he",
    image: "http://127.0.0.1:8000/media/structures/IMG_6569.JPG",
  },
  {
    name: "Карелина-Симсон Юлиана Олеговна",
    position: "N",
    phone_number: "+7 (8512) 66-74-62",
    department: "dc",
    image: null,
  },
  {
    name: "Котелевский Кирилл Александрович",
    position: "N",
    phone_number: "+7 (8512) 66-74-61",
    department: "pr",
    image: "http://127.0.0.1:8000/media/structures/IMG_6567.JPG",
  },
  {
    name: "Поволоцкая Елена Владимировна",
    position: "S",
    phone_number: "+7 (8512) 66-74-61",
    department: "pr",
    image: null,
  },
  {
    name: "Попова Евгения Павловна",
    position: "S",
    phone_number: "+7 (8512) 66-74-61",
    department: "pr",
    image: null,
  },
  {
    name: "Лукин Роман Юрьевич",
    position: "N",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Архангельская Наталья Витальевна",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Гриднев Сергей Владиславович",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Очеретная Анастасия Дмитриевна",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Сайгутина Оксана Евгеньевна",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Скокова Анна Сергеевна",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Шинкаренко Александр Владимирович",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Сандриков Алексей Алексеевич",
    position: "Z",
    phone_number: "",
    department: "he",
    image: null,
  },
  {
    name: "Науметов  Роман Равилевич",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Нугманова Марина Каримовна",
    position: "С",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Пак Мейрамбек",
    position: "S",
    phone_number: "",
    department: "it",
    image: null,
  },
  {
    name: "Джубаньязова Дания Коптлеуовна",
    position: "A",
    phone_number: "",
    department: "pr",
    image: null,
  },
  {
    name: "Колесникова Виолетта Андреевна",
    position: "O",
    phone_number: "",
    department: "gl",
    image: null,
  },
  {
    name: "Носков Никита Юрьевич",
    position: "O",
    phone_number: "",
    department: "gl",
    image: null,
  },
  {
    name: "Попов Андрей Юрьевич",
    position: "I",
    phone_number: "",
    department: "gl",
    image: null,
  },
  {
    name: "Порунцова Галина Александровна",
    position: "R",
    phone_number: "",
    department: "dc",
    image: null,
  },
  {
    name: "Урембаев Роман Робертович",
    position: "L",
    phone_number: "",
    department: "dc",
    image: null,
  },
];
export default structure;
